server:
  port: 9002
spring:
   application:
     name: eureka-register
   profiles:
     active: test


eureka:
  instance:
    hostname: 192.168.12.124
  client:
    service-url:
      defaultZone: http://192.168.12.124:9002/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000


debug: true
